-- O schema canônico da SEXTA é versionado em:
-- supabase/migrations/20260901193718_harden_sexta_core.sql
--
-- A migration é idempotente, cria todas as tabelas, índices, grants e RLS.
-- Em um projeto novo, aplique as migrations e cadastre somente o SHA-256 da
-- SEXTA_DATA_API_KEY em private.sexta_api_keys.key_hash. Nunca grave a chave
-- bruta no banco nem no repositório.
